روی:
  فشار دادن:
    شاخه‌ها:
      - اصلی
  workflow_dispatch:

مشاغل:
  ساختن:
    اجرا می‌شود: اوبونتو-آخرین نسخه

    مراحل:
      - نام: مخزن پرداخت
        موارد استفاده: actions/checkout@v3

      - نام: راه‌اندازی Node.js
        موارد استفاده: actions/setup-node@v3
        با:
          نسخه-گره: 18

      - نام: نصب وابستگی‌ها
        اجرا کنید: |
          cd ./iranstock
          npm install

      - نام: نصب EAS CLI
        اجرا کنید: npm install -g eas-cli

      - نام: ساخت APK
        اجرا: |
          cd ./iranstock
          eas build --platform android --profile development --non-interactive
        پاکت:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
